[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
logic = { path = "../logic" }
wgpu = { workspace = true }
bytemuck = { version = "1.19.0", features = ["derive"] }
glam = "0.29.2"
glyphon = "0.7.0"
cosmic-text = { version = "0.12", features = ["std", "swash"], default-features = false }
minipng = "0.1.1"
hecs = { workspace = true }
