[package]
name = "client_native"
version = "0.1.0"
edition = "2024"

[dependencies]
sdl3 = { version = "0", features = ["mixer", "raw-window-handle", "build-from-source"] }
pollster = "0.4.0"
nanotime = { path = "../nanotime" }
client = { path = "../client" }
logic = { path = "../logic" }
wgpu = { workspace = true }
